name: Test CI
on:
  push:
    branches: [ dev , master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Change gradlew permissions
        run: chmod +x gradlew
        
      - name: Run Gradle build
        run: ./gradlew clean build test
